server:
  port: 8088
  context-path: /votedemo
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  profiles:
    active: testoracle

mybatis:
  mapper-locations: classpath*:com/baizhi/vote/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.vote.entity




