server:
  port: 8088
  servlet:
    context-path: /votedemo
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  profiles:
    active: test
mybatis:
  mapper-locations: classpath*:com/baizhi/vote/mapper/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&characterEncoding=utf8
    username: root
    password: root


